GET http://localhost:5000/users
###
GET http://127.0.0.1:5000/blog

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "nik": "35516636551",
    "name": "maulana",
    "email": "maulana@gmail.com",
    "password": "admin123",
    "confPassword": "admin123",
    "role": ""
}

###
POST http://localhost:5000/admin
Content-Type: application/json

{
    "name": "Muhammad Fadli",
    "email": "iwan@gmail.com",
    "password": "admin123",
    "confPassword": "admin123",
    "role": ""
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "name": "maulana",
    "password": "admin123"
}

###
POST http://localhost:5000/forgot
Content-Type: application/json

{
    "email": "iwan@gmail.com"
}

###
POST http://localhost:5000/reset
Content-Type: application/json

{
    "token": "ab11761c94e2bb40f55d3dda7a7612792dfd0f53",
    "newPassword": "123"
}

###
POST http://localhost:5000/pengajuan
Content-Type: application/json

{
    "banyak_sampah_kg": 5,
    "metode_pembayaran": "gopay"
}

###
DELETE http://localhost:5000/logout 