GET http://localhost:5000/users
###
GET http://127.0.0.1:5000/blog

###
POST http://localhost:5000/register
Content-Type: application/json

{
    "nik": "35516636551",
    "name": "iwan",
    "email": "iwan@gmail.com",
    "password": "admin123",
    "confPassword": "admin123",
    "role": ""
}

###
POST http://localhost:5000/admin
Content-Type: application/json

{
    "name": "Muhammad Fadli",
    "email": "iwan@gmail.com",
    "password": "admin123",
    "confPassword": "admin123",
    "role": ""
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "name": "iwan",
    "password": "123"
}

###
POST http://localhost:5000/forgot
Content-Type: application/json

{
    "email": "iwan@gmail.com"
}

###
POST http://localhost:5000/reset
Content-Type: application/json

{
    "token": "19fcff3a7b735746156719acdcf247ccf1fd0623",
    "newPassword": "123"
}

###
GET  http://localhost:5000/pengajuan

###
GET  http://localhost:5000/pengajuans
###
POST http://localhost:5000/pengajuan
Content-Type: application/json

{
    "banyak_sampah_kg": 13,
    "metode_pembayaran": "cod"
}

###
DELETE http://localhost:5000/logout 